### ISSUE TITLE
Permission denied when trying to access /badc/ecmwf-era-interim/data/gg/as/ with a sci server

### ISSUE THREAD

**Issue by clacap-CEH** [cedadev/jasmin-workshop#62]
ex04

**Comment by agstephens** [comment]
Hi @clacap-CEH, this is most likely because you are not using a `training` account to run the exercise. The training accounts should all have access to the `open` Unix group and should therefore be able to read the data. If you are using your own JASMIN account you can connect it to a CEDA account in order to gain the same access, see:

https://help.jasmin.ac.uk/article/4552-update-a-jasmin-account#linkceda
